---
- name: Update System
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install OpenSlides Dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - sudo
  - python-django
  - python-beautifulsoup4
  - python-html5lib
  - python-reportlab
  become: yes

- name: Install nginx
  when: openslides_nginx_domains or openslides_nginx_global
  become: yes
  pacman:
    name: nginx
    state: present

- set_fact:
    pip_executable: pip
    openslides_distro_fround: true
    openslides_bin: /usr/bin/openslides
