---
- name: Activate universe sources
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://archive.ubuntu.com/ubuntu xenial main universe

- name: Update System
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install OpenSlides Dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python3-bs4
  - python3-djangorestframework
  - python3-html5lib
  - python3-django-jsonfield
  - python3-natsort
  - python3-reportlab
  - python3-roman
  - python3-setuptools
  - python3-sockjs-tornado
  - python3-whoosh
  - python3-pypdf2
  - python3-pip

- name: Install nginx
  when: openslides_nginx_domains or openslides_nginx_global
  become: yes
  apt:
    name: nginx
    state: present

- set_fact:
    pip_executable: pip3
    openslides_distro_fround: true
    openslides_bin: /usr/local/bin/openslides
