---
- name: Install packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - hostapd
  - dnsmasq

- name: Configure wlan0
  become: yes
  copy:
    dest: /etc/systemd/network/wlan0.network
    content: |
      [Match]
      Name=wlan0

      [Network]
      Address={{ pi_wlan_ap_ip }}
  notify:
  - restart network

- name: Configure hostapd
  become: yes
  copy:
    dest: /etc/hostapd/hostapd.conf
    content: |
      interface=wlan0
      ssid={{ pi_wlan_ap_ssid }}
      channel={{ pi_wlan_ap_channel }}
      country_code=DE
      ieee80211n=1
      wmm_enabled=1
      hw_mode=g
      ignore_broadcast_ssid=0
      {% if pi_wlan_ap_password %}
      auth_algs=1
      wpa=2
      wpa_key_mgmt=WPA-PSK
      rsn_pairwise=CCMP
      wpa_passphrase={{ pi_wlan_ap_password }}
      {% endif %}
    mode: 600
  notify:
  - restart hostapd

- name: Start and enable hostapd
  become: yes
  service:
    name: hostapd
    state: started
    enabled: yes

- name: Configure dnsmasq
  become: yes
  copy:
    dest: /etc/dnsmasq.conf
    content: |
      interface=wlan0
      no-dhcp-interface=eth0
      dhcp-range={{ pi_wlan_ap_dhcp_range }},24h
      dhcp-option=option:dns-server,{{ pi_wlan_ap_ip }}
      {% for entry, value in pi_wlan_ap_dns_entries.items() %}
      address=/{{ entry }}/{{ value }}
      {% endfor %}
  notify:
  - restart dnsmasq

- name: Start and enable dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: started
    enabled: yes
