---
- name: restart hostapd
  become: yes
  service:
    name: hostapd
    state: restarted

- name: restart dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: restarted

- name: restart network
  become: yes
  service:
    name: systemd-networkd
    state: restarted
